version: "3"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "8040:80"
    volumes:
      - ./public_html/neloreaguafriajg.com.br:/app

  db:
      image: mysql:5.7
      container_name: neloreaguafriajg-db
      restart: unless-stopped
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_USER: joaquim
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_PASSWORD: 123456
          MYSQL_DATABASE: neloreaguafriajg_development
      ports:
        - "3306:3306"
      volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini